version: '3'

services:
  db:
    image: mongo
    volumes:
      - mongo_test_data:/data/db
    ports:
      - "27017:27017"
    # restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: secret

  shell:
    image: mongo
    depends_on:
      - db

volumes:
  mongo_test_data:
# To remove:
# Or: docker-compose rm -v db

